# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cache_pb2 as cache__pb2


class RickAndMortyServiceStub(object):
    """Definición del servicio para interactuar con la API de Rick and Morty
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCharacter = channel.unary_unary(
                '/RickAndMortyService/GetCharacter',
                request_serializer=cache__pb2.GetCharacterRequest.SerializeToString,
                response_deserializer=cache__pb2.Character.FromString,
                )


class RickAndMortyServiceServicer(object):
    """Definición del servicio para interactuar con la API de Rick and Morty
    """

    def GetCharacter(self, request, context):
        """Método para obtener un personaje dado su ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RickAndMortyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacter,
                    request_deserializer=cache__pb2.GetCharacterRequest.FromString,
                    response_serializer=cache__pb2.Character.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RickAndMortyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RickAndMortyService(object):
    """Definición del servicio para interactuar con la API de Rick and Morty
    """

    @staticmethod
    def GetCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RickAndMortyService/GetCharacter',
            cache__pb2.GetCharacterRequest.SerializeToString,
            cache__pb2.Character.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
