# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\"s\n\tCharacter\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07species\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\r\n\x05image\x18\x07 \x01(\t\"!\n\x13GetCharacterRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32I\n\x13RickAndMortyService\x12\x32\n\x0cGetCharacter\x12\x14.GetCharacterRequest\x1a\n.Character\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHARACTER']._serialized_start=15
  _globals['_CHARACTER']._serialized_end=130
  _globals['_GETCHARACTERREQUEST']._serialized_start=132
  _globals['_GETCHARACTERREQUEST']._serialized_end=165
  _globals['_RICKANDMORTYSERVICE']._serialized_start=167
  _globals['_RICKANDMORTYSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
